<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mtt_driver</name>
  <version>0.1.0</version>
  <description>ROS 2 driver for MTT-154 with C++ SocketCAN, odometry, and teleoperation components</description>
  <maintainer email="alex.chorel-campanozzi@ecn.forces.gc.ca">admassistant</maintainer>
  <license>Apache License 2.0</license>

  <!-- Build tools -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- C++ core ROS deps -->
  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>std_srvs</depend>
  <depend>libboost-system-dev</depend>
  <depend>libboost-thread-dev</depend>

  <!-- Custom message / service packages -->
  <depend>mtt_msgs</depend>
  <depend>mtt_interfaces</depend>

  <!-- Component deps -->
  <exec_depend>joy_linux</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>mtt_control</exec_depend>

  <!-- Test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ros</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
